apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tautulli-api-key-secret
  namespace: prometheus
spec:
  encryptedData:
    apikey: AgCk1646PUni4euOUNyPC7zbI439kWAteCOhUt594Vx5Ypfzh2lV7FCU4xwsF3go7pN1YjXwuHPPwO+CTL9i10O2A6W1LkeG4U8mBQDrxWZev+gM2KZtYJxv6acUm/duo/0ChIMfs4Ilsu4pbrgJi6CqdmZKDoUWa2YyG2DpG+D1EPg3s7FPcQ73Ib+llRJS6+nAOwsyRH0dJkndWBGjIfQkCIN/0erjSGrhqL/H87dCDBymN6tdSBZqEI5QUwRGeNOs3+9ydDc09em1LoFP3DmyBmh0Exu8vAGgmdM3NxcMD+qg3IqjloX3LOOVgoerqSIe1EiqGOIN2kly2BKrHXTE2QZEzRTg1ICL9QEELm5E2PEazULpmIwhEA+MeBqc0thEuUW+8lDr5n4sBPhBuxDPzjiLtdlOt1LxFZErCC8kf1/4e/aFqSpwvMzJoHJv2rW4n7Cyizueen/dx0/he0qShB0bdKpeMt3kjPDz58JRIzqIlg53r9E7YbmPOIEpqeuvzNXRsh5dTFdL5SER/TNmXFhv4UWbNnP1Ug/+u/M9Rb5sWkHrDtKxqGcnwDa0Nr/Fy25g9eDgkUr2cqz/DTSnCGWeWZDpgN7j+v6fcP9XwbWEbOUjY2QijIC5/263UqlhIh131zsvwXxXK+OBOz36bJMziy7kyrtkN46Ry2TEFVTiq0cBOqX2LLQRrJt0STzqZmT+PQdIAfJRRvmFTWK40G1fNis11CsV79prTn2nHw==
  template:
    metadata:
      creationTimestamp: null
      name: tautulli-api-key-secret
      namespace: prometheus
    type: Opaque
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    release: prometheus
  name: tautulli-exporter
  namespace: prometheus
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: metrics-tautulli
  namespaceSelector: {}
  selector:
    matchLabels:
      app: tautulli-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-exporter
  namespace: prometheus
  labels:
    release: prometheus  
    app: tautulli-exporter
spec:
  selector:
    app: tautulli-exporter
  ports:
    - protocol: TCP
      port: 9487
      targetPort: 9487
      name: metrics-tautulli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-exporter
  namespace: prometheus
  labels:
    release: prometheus
    app: tautulli-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tautulli-exporter
  template:
    metadata:
      labels:
        app: tautulli-exporter
    spec:
      containers:
      - name: tautulli-exporter
        image: nwalke/tautulli_exporter
        env:
        - name: TAUTULLI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tautulli-api-key-secret
              key: apikey
        - name: TAUTULLI_URI
          value: http://tautulli.monitoring.svc.cluster.local:8181
        ports:
        - containerPort: 9487