apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fgc-secrets
  namespace: convenience
spec:
  encryptedData:
    EG_EMAIL: AgA4T+z8kCWHZM+wicV65fHCq/XVShTV5LqvjG964cIi+zboqZtZAHWsmKjK9kwGG1vFdazDFYupStzprXnD1vO53aKl5MN0W5lLgGyO87xn6lBpPV8acwTkN/5Y4WdH2rvYihQx/rbqqZjCvLEVcnscYzaWrkc54CtV98aKrFoPZXUZGCkdxj5mxfw1ovayTewWeYDShJRwWTinfdVfJrfjVlo8tGOggE6fMulYuh0KcyGxAgQiG8Jpxh365s9/kj8kCF+bmWS7YkP8TPS2OxnKYiMeydHoslUlFzfvqqldknL5vX60fSGPA/9dRE9ld2QnGibuzjH1peXMyno80FaY+jHLUJhlN9c+NDGAYReL9hrlXtyotPeY/qecuuh3LX7t96ohpgPV6km8xd5u1SeRu15Fauq+q1KTxTiRwJ3iawkVnY/GaWvtKgypZgPSC9wDTptsGTmu4hs4adF7E3AsJXkdop4HqKturJvak3/ppSVN9kIAd6aD47j5IzjpBN0DD7HBuec9C2AG6eWultuxNSYakHFJhLEOckpv1htDmVGlNHa/K5a4AV+ZiI5HxSpl1MP9KoMvR2YNrVhpKFTmoCVPMDpHPzgG92hEO2rFuhmrnUTpd0bPTx08Q8LInbXjhuZcgbrlKRgZfj6Zz50eiCjKM1KoNUENZsUfjJNQ2difUZlgAdzd/3lTXnnmYTVGK6edlFEbJB+GHA0+hehq
    EG_PASSWORD: AgA9XrHu/Z1mDOWpcb4GQoNooMxFmEtBI6hCl9p829B03G+b77qXfpEeP5KsUlq7Flv9hKyU/gjl4aJ//6JfXm4rzLJWMW/ruH0EKty4tM8PPppzKuWuoFSd5yPHxT5vzePz8klnJk9hYtTgFLYhNC9CEiuvI3RJC79B9TB9cLh+DBgtxrElwVtfjVMRVYgBeN6cVEWsOhZPWGJwl7DOUqfHhHT/4YK80HuPnpXw9VKRD2dHoGE8wYN1JRcvnP0mXCQiRTRJCu78LicsZMHGlDJbZWE7mkhOzjJ+9r7PJSLefarPToqSzA8or73rlnI06wLSuN7HdoI8Ao0wZQN3dDWLYZKDbw4BjejYAKFAfwEV5x2beRGmuJfpH6OaRYiOg9nDyH26lf7GIUjWuKWAL+v+qXmWSoEd3fJ9uwsLxA10080ud3/y087QvSvDmj5x5lsHxl6jAp/OHVkYwFmVBnDlRsdM05r9E9pzRlNbucdJQrTFZ9QdIYZMDrGAnHCSzxeNHjmeaP4nmKOiQzXHIm09YojaeXxuOmOycx8Vc/1hAeR3qP+VSNSjG10PFdZyqNQAdLLhJ+zhJj3nCAnTJI94a7V27ydFKL2MWYviWYPwEePdiwq1ypn5z80Sf6ElBbm5tDY5dY5Z/AEKjcKa87Wu5eS0pq0w6iodnspOlIeyaUGN2CDcDedqIp9c5vy25YLFzowcXpHvM5M=
    GOG_EMAIL: AgCaQpvv9Ras3pIjRN3FNd2FL0wxEFimlIqg2bcNZk/81i7GmKrYNuoEsN5O04T5W7I//6aIV9kbPNaxurdbTiXhEgJP9Yy06p1DGrLMP1XQ8gVa7tYru8PZjjwy4MPp7ujO09ZVLVuSR6BErHrJTfDqTiI2Wb+mXPI8cvMyRg7G+417E5UnUJjg5of713dxmJpbNUzhfxRfMdYcFTnqoI369QTrgOTKbE9AxOf5hhGe1vbwQH57Bn/4BAxqrhb/jhG01vwg6npSe8CoSoxfxZrFqucraAZNsPCaogT9PLCTHGgk2ib7/uzUFVPAdWe2cOeMDKqnINI2NQdaevZvNLJm0jk6UELZS8FbiFUXBSh2S1BJPrc01+PE4oATOSraofOuQ2X4oBS2ta0mJU+OZG2oZqq2uWQQnBFdyPPDUX2AzwgvAIJN+6nFFk+I5Tdg3o0CJfsiBHBEO8n0ACh7F/15c1yJF915lAgm+K9I/BlygHtzEqCmrCrRupI2/7eYxdI9d+QM8zPpad73MOL+/jkfvjuzHGv5vhF2v2OL+0goJoA3Ulzifo2FM//Ok/6aV3N6+07ery4ws54vM6Q2NVmd0ADQNtrF1VupygQbbjgD0uyoZIngCiqCfAp6zepj9GZGLOMlykn9BX6hM/NjH+c98btxcIBlH5oFJPa4wiMn7UZ04ie80g+d72sQ8H0nu0bngy66QEYw+1PYx7GK+DUe
    GOG_PASSWORD: AgDMqnWE3N1z+0V9xDYSWJvtuHF0fVuQsp7CfEg/zQzSjZYhusFnUmW1d9n41AOLRdXwfQF2Uk4hMnQvhFKEak/SvMKQjspdtfiPhGx3G/MzNv8W/uLBsHjevBU2C67wwS2ClgApjh29gSBLWqR7sx4yE8cTHMBQ/Qs9L4VeXm7IOd4MMF1qHpZhPYF5BPcyQx7b6/CxN9lNbPsylBIcreVwV2BoGgAtvQMky5t8/2Pamp18kAkeJ+cmaYMtvhsTEvUX4ooCwCf9VAWDbSHtq3Xc//CWywEnAAOKMMpN1aGTWrfguOIB2SwTVLzsSF1wsO5/BEm+fC0ZCTLdUuHKXqY1iI7cp9RGPQ4xc8Hnw/qaB0NkI0SUaGSqtOcIM44JdLUkkQuwnypbr6PDNiND8EP22pJBgh67cQnPxB0v2KjbIXSkuvq5EPm8BNPRbYkE8tAnySouATTu7+8vrSd+Wa/i9cfSvh2eD5GpuLFf5YeES88R2PiVLCdLOh8ej6cL3ecRKA9MEs5dIaNVHbOd9QQR8vaFtphv5fuuedpZ0Ep020i6Nob4rbsXRPzghEDYy1tKpGeOI93RtR3XtohDEOQtvh6kFjnoHfCWddzsCyjhTVChb6LnhQ00hIAMhvT134k1pQhBhCvr/gxTE+mXKCDkJZPbue95vSNoID84ooWoMwAWCVNfk0hnzv8t91U/+vIIAorbSq8Wlrg=
    PG_EMAIL: AgDDiRe9jaQVaCFoZjpPx4rQQ7x8CXwNbsT/wPZvi9qePSPLaNymvHJCmD5DaMcSIdtxH+NgLkHRsq3CSIQGpyP+Ei0WeCBAYe9Rcod37BZZ4Ry2DuPQq64WXSyP4nK1N1MS27P5jnYbhq6HZWv1KfgY+xI9sY+teG7yue7OihvnBtbuDCoOqJaFG5YFRmrPYDfZiHcP1vNPh00XSt+4NFXjCZmx/VNbxJzd7M/SZKJQ3XEu8Nwh0cegAzqkEN6LeWXCbtKyHZbLhP0WLQIOgwWmzXV+zNkjq5E4ga56CA4tMvrbhyjQSS4iE8d2oCeiy8szlV6IimpcAck5ACeflge8E8EatFjCc6h/aKHtXIrJ7DgJOnRYJvYEpBoB1F5VGZhyj0LjprLiQk2GKECJ7ekGe9etEdzLsTHf9IbO+T8PmauJmGO2cTPpVt/kFWMceRMmijjXEOBXRPMi6MDboRZtDmlL37j1cHHtK+cjsXLJOKtrY58i0vnD//9kOjRgKsi/dL+lM/lcFnpn87k0has2U1t4041lJmd/45+h3qAlVq7hcsfbgjZg8YW0bk7CMaU9WuTbr4QwUVktPz2hUATKmQptUoyW7XVIJ9X19KIsLcw6or5cAMdIfGhP1v3O7ABVWVtilmj7Mq6ucWnbtpiGTo6HbHY5rcCZ00b9mcjndmrTh59MAaPuUjumHFA4BU54ep8RSeBs1iHfMXjSX4Y7AWE=
    PG_PASSWORD: AgCbaipnlcdw5HFFfTRjQAloQPSWBkBDXfwRqgNHPs0hGXmeXqt/9VKUVGT45QN8NmVIUiYSZw5NIuYNkiQFtREKpiEdrPFW6AKOHHh0dd0GB0EkeIGMZrlywHMUvUiQxQyAxplemBPjMUV9NQD/hD3BNNi/FFK670NL4AKfYjVaM6jEMfKQPEGOsPoCjYKIvrJrusRaHiduCGHMWJqQ+dgK+1j15A2Jq3ot5uoaIUCVNjJMSwRZoejRvNZctVd7zZBoZqai+HZUKzAulGo7vABou2ta2QagiH6Z08xY+MRxR3QTSymeBEkJ62i5QGTwq3XeA/xKhX9hZEByJ6JxpWEXVhIoXWLKaPpTdHjkBvkMk5DrHuiFojLAX3BaZhvvn+6TpyTDnN+WKs3bBOFj+qbHWcZlkInI++AnF9pXzVu9+nNeWLd6zYHADrnPybq0MCFGV+jl0f9qP8Ml+sJKKEywKrIp4cn3oi3xrtOWSAIA5Gjcf7VQdis8mIZH0b7q2Ex6yNDj5EP8HqaVlwMlE5fwfePNCBsWFb1JVTAmApFsogN/fd+YvM9Nb8j6NqXHSu5+wzPvs5yT/ukYLH52xLIrNXJrF+bQmjuan+/5xhru/UV1oO/Eak3wB1n5F0ckm05HHX+KF69TthiTxpyEFcTF7MvGaomZdc1d8pr/7A+iMz3NOSSvvPNl2juSLchLmYsfXsR6lnpq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fgc
      name: fgc-secrets
      namespace: convenience
    type: Opaque
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: free-games-claimer
  namespace: convenience
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: free-games-claimer
        spec:
          restartPolicy: OnFailure
          containers:
          - name: free-games-claimer
            image: voglerr/free-games-claimer@sha256:7ed15e6e4a514f08d0e4ae1017ec3c5008ce4f1bd68bafb3015fde4f6a3e872d
            imagePullPolicy: IfNotPresent
            env:
            - name: EG_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: EG_EMAIL
            - name: EG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: EG_PASSWORD
            - name: PG_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: PG_EMAIL
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: PG_PASSWORD
            - name: GOG_EMAIL
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: GOG_EMAIL
            - name: GOG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fgc-secrets
                  key: GOG_PASSWORD                     
            ports:
            - containerPort: 6080
            volumeMounts:
            - name: fgc-volume
              mountPath: /fgc/data
          volumes:
          - name: fgc-volume
            persistentVolumeClaim:
              claimName: fgc-pvc
  successfulJobsHistoryLimit: 1
