apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: nextcloud-config-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config-pvc
  namespace: backup
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  volumeName: nextcloud-config
  storageClassName: longhorn 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    path: /volume1/NextCloud
    server: 192.168.50.50
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nextcloud
  annotations: 
    prometheus.io/port: "9205"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9205
    targetPort: metrics
  selector:
    app.kubernetes.io/name: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: backup
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.197
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: nextcloud
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  namespace: backup
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: linuxserver/nextcloud:29.0.5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "300m"
            memory: "256Mi"        
        env:        
        - name: MYSQL_HOST
          value: "mariadb.databases.svc.cluster.local:3306"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: db-password
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: nextcloud-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nc.104-400mvb.ca 192.168.50.197"
        - name: NEXTCLOUD_DATA_DIR
          value: "/data"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Toronto"
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status.php
            port:  443
            scheme: HTTPS
            httpHeaders:
            - name: Host
              value: "192.168.50.197"
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status.php
            port:  443
            scheme: HTTPS
            httpHeaders:
            - name: Host
              value: "192.168.50.197"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: nextcloud-config
          mountPath: /config
        - name: nextcloud-data
          mountPath: /data
      volumes:
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: metrics-exporter
        image: "xperimental/nextcloud-exporter:0.7.0"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"        
        env:
        - name: NEXTCLOUD_USERNAME
          valueFrom:
            secretKeyRef:
              name: nextcloud-metrics
              key: nextcloud-username
        - name: NEXTCLOUD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-metrics
              key: nextcloud-password
        - name: NEXTCLOUD_SERVER
          value: https://nc.104-400mvb.ca
        - name: NEXTCLOUD_TIMEOUT
          value: 5s
        - name: NEXTCLOUD_TLS_SKIP_VERIFY
          value: "false"
        ports:
        - name: metrics
          containerPort: 9205
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
