---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud
  namespace: backup
subsets:
  - addresses:
      - ip: 192.168.50.197
    ports:
      - name: https
        port: 443
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: backup
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: backup
  labels:
    name: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    acme.cert-manager.io/http01-edit-in-place: 'true'
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "192.168.50.0/24"
spec:
  ingressClassName: nginx
  rules:
    - host: nc.104-400mvb.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 443
  tls:
    - hosts: ['*.104400.xyz']
      secretName: wildcard.104400.xyz-tls
    - hosts: ['*.104-400mvb.com']
      secretName: wildcard.104-400mvb.com-tls
    - hosts: ['*.104-400mvb.ca']
      secretName: wildcard.104-400mvb.ca-tls
