---
apiVersion: v1
kind: Endpoints
metadata:
  name: omada-controller
  namespace: omada-controller
subsets:
  - addresses:
      - ip: 192.168.0.199
    ports:
      - name: https
        port: 8043
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: omada-controller
spec:
  ports:
    - name: https
      port: 8043
      protocol: TCP
      targetPort: 8043
  clusterIP: None
  type: ClusterIP
