apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data
  labels:
    argocd.argoproj.io/instance: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: uptime-kuma-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: uptime-kuma-data-pvc
  labels:
    argocd.argoproj.io/instance: uptime-kuma  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: uptime-kuma-data
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: uptime-kuma
  labels:
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.17
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: uptime-kuma
  labels:
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
      app.kubernetes.io/instance: uptime-kuma
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uptime-kuma
        app.kubernetes.io/instance: uptime-kuma
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: uptime-kuma
          image: "louislam/uptime-kuma:1.23.16"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"          
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: America/Toronto
            - name: UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
              value: "0"
            - name: UPTIME_KUMA_PORT
              value: "3001"
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 30
            failureThreshold: 30
            timeoutSeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data-pvc
