---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: home-assistant-config-pv
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: home-assistant-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: automation
  name: home-assistant-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-config-pv
  storageClassName: longhorn 
---
apiVersion: v1
kind: Service
metadata:
  namespace: automation
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.195
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  - port: 1984
    targetPort: 1984
    protocol: TCP
    name: go2rtc
  - port: 8555
    targetPort: 8555
    protocol: TCP
    name: webrtc
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: automation
  name: home-assistant
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  serviceName: home-assistant 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      enableServiceLinks: true
      initContainers:
        - name: wait-for-db
          image: ghcr.io/patrickdappollonio/wait-for:latest
          env:
          - name: MARIADB_HOST
            value: "mariadb.databases.svc.cluster.local:3306"           
          args:
          - --host="$(MARIADB_HOST)"
          - --verbose       
      containers:
        - name: home-assistant
          image: "homeassistant/home-assistant:2023.11.3"
          imagePullPolicy: IfNotPresent         
          resources:
            limits:
              cpu: "400m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"          
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST            
          env:
            - name: TZ
              value: "America/Toronto"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
              host: ha.104-400mvb.ca
            initialDelaySeconds: 30
            failureThreshold: 60
            timeoutSeconds: 25
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 30
            failureThreshold: 60
            timeoutSeconds: 25
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 20
            failureThreshold: 60
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true            
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config-pvc      
        - name: localtime
          hostPath:
            path: /etc/localtime