---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: changedetection-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: changedetection-data
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: changedetection-data-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: changedetection-data-pv
---
apiVersion: v1
kind: Service
metadata:
  name: changedetection-io
  namespace: monitoring
  labels:
    app.kubernetes.io/service: changedetection-io
    app.kubernetes.io/instance: changedetection-io
    app.kubernetes.io/name: changedetection-io
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: changedetection-io
    app.kubernetes.io/name: changedetection-io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: changedetection-io
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: changedetection-io
    app.kubernetes.io/name: changedetection-io
spec:
  serviceName: changedetection-io
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: changedetection-io
      app.kubernetes.io/instance: changedetection-io
  template:
    metadata:
      labels:
        app.kubernetes.io/name: changedetection-io
        app.kubernetes.io/instance: changedetection-io
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      terminationGracePeriodSeconds: 0
      containers:
        - name: changedetection-io
          image: ghcr.io/dgtlmoon/changedetection.io::0.44.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PLAYWRIGHT_DRIVER_URL
              value: ws://localhost:3000
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 5000
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 5000
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: 5000
            timeoutSeconds: 1
          volumeMounts:
            - name: datastore
              mountPath: /datastore
        - env:
          - name: DEFAULT_BLOCK_ADS
            value: "true"
          - name: DEFAULT_STEALTH
            value: "true"
          - name: ENABLE_DEBUGGER
            value: "false"
          image: browserless/chrome:latest
          name: browserless
          ports:
          - containerPort: 3000
            name: browserless
      volumes:
        - name: datastore
          persistentVolumeClaim:
            claimName: changedetection-data-pvc
