---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: vaultwarden-data
  labels:
    argocd.argoproj.io/instance: vaultwarden
spec: 
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: vaultwarden-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: convenience
  name: vaultwarden-data-pvc
  labels:
    argocd.argoproj.io/instance: vaultwarden  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: vaultwarden-data
  storageClassName: longhorn 
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: convenience
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 3012
    targetPort: websocket
    protocol: TCP
    name: websocket
  selector:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: convenience  
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden
spec:
  serviceName: vaultwarden
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: vaultwarden
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true     
      initContainers:
        - name: wait-for-db
          image: ghcr.io/patrickdappollonio/wait-for:latest
          env:
          - name: MARIADB_HOST
            value: "192.168.50.163:3306"           
          args:
          - --host="$(MARIADB_HOST)"
          - --verbose
          - --every=5s
          - --timeout=600s               
      containers:
        - name: vaultwarden
          image: "vaultwarden/server:1.33.2"
          imagePullPolicy: IfNotPresent          
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"          
          env:
            - name: DATA_FOLDER
              value: config
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secrets
                  key: ADMIN_TOKEN
            - name: DATABASE_URL
              value: mysql://vaultwarden:vaultwarden@192.168.50.163/vaultwarden?charset=utf8mb4
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: websocket
              containerPort: 3012
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
        - command:
            - /bin/sh
            - '-c'
            - |
              apk add --no-cache mysql-client openssh
              echo "Starting MariaDB monitor sidecar..."
              mariadb_down=0
              while true; do
                # Check MariaDB readiness
                if mysqladmin ping -h 192.168.50.163:3306 --password=$MARIADB_ROOT_PASSWORD --silent; then
                  if [ "$mariadb_down" -eq 1 ]; then
                    echo "MariaDB has recovered. Restarting Vaultwarden..."
                    # Restart Vaultwarden StatefulSet via SSH
                    sshpass -p "SSHPASS" ssh -o StrictHostKeyChecking=no root@192.168.50.200 "kubectl rollout restart statefulset Vaultwarden -n convenience"
                    mariadb_down=0  # Reset the flag
                  fi
                  echo "MariaDB is up and healthy."
                else
                  echo "MariaDB is down."
                  mariadb_down=1  # Set the flag to indicate MariaDB is down
                fi
                sleep 60  # Check MariaDB status every 60 seconds
              done
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: vaultwarden-secrets
            - name: SSHPASS
              valueFrom:
                secretKeyRef:
                  key: sshpass
                  name: vaultwarden-secrets                 
          image: 'alpine:latest'
          imagePullPolicy: Always
          name: sidecar-mariadb-monitor
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File           
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
